name: swiper_csc_picker
description: "A Flutter package to display and search countries, states, and cities in Arabic, English, or the native language worldwide."
version: 0.0.5
homepage: https://github.com/vgarfi/swiper_csc_picker.git

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - lib/assets/
